# Generated by Django 4.1.7 on 2023-05-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='project_image_path',
            field=models.ImageField(upload_to='order_image/'),
        ),
    ]
